<a href="https://colab.research.google.com/github/hubblej28/curso_python_utec/blob/main/Laboratorios/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Llamar a la libreria

import numpy as np

In [2]:
#Crear un arreglo en numpy

arr_1 = np.array([2,4,6])

print(f"El arreglo es \n{arr_1}")
print(f"El tipo de objeto es \n {type(arr_1)}")

El arreglo es 
[2 4 6]
El tipo de objeto es 
 <class 'numpy.ndarray'>


In [3]:
arr_2 = np.array([[0,1,2,3],[4,5,6,7], [8,9,10,11]])
print(f"El arreglo es \n{arr_2}")
print(f"El tipo de objeto es {type(arr_2)}")

El arreglo es 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
El tipo de objeto es <class 'numpy.ndarray'>


In [8]:
lista_1 = [[0,1,2,3],[4,5,6,7], [8,9,10,11]]
print(f"El primer elemento de la lista de listas es {lista_1[0]}")

print("*** Operaciones matemáticas con la lista***")

print(f"El valor mínimo es {min(lista_1[0])}")
print(f"El valor máximo es {max(lista_1[0])}")
print(f"El valor total es {sum(lista_1[0])}")
print(f"El valor promedio es {sum(lista_1[0])/len(lista_1[0])}")

El primer elemento de la lista de listas es [0, 1, 2, 3]
*** Operaciones matemáticas con la lista***
El valor mínimo es 0
El valor máximo es 3
El valor total es 6
El valor promedio es 1.5


In [11]:
## Operaciones con 2 listas
l1 = [1,2,3]
l2 = [4,5,6]

print(f"El resultado de trabajar con dos listas y el símbolo + es \n{l1 +l2}\n")
print(f"El resultado de sumar ambas listas es \n{sum(l1)+sum(l2)}")

El resultado de trabajar con dos listas y el símbolo + es 
[1, 2, 3, 4, 5, 6]

El resultado de sumar ambas listas es 
21


In [12]:
# Operaciones matemáticas con arreglos de NumPy
arr_4 = np.array([1,2,3,4,5])
arr_5 = np.array([10,20,30,40,50])
print(f"El primer arreglo es \n{arr_4}")
print(f"\nEl segundo arreglo es \n{arr_5}")

El primer arreglo es 
[1 2 3 4 5]

El segundo arreglo es 
[10 20 30 40 50]


In [13]:
arr_r1 = arr_4 + arr_5
arr_r2 = arr_5 - arr_4
print(f"La suma de ambos arreglos es \n{arr_r1}")
print(f"\nLa diferencia de ambos arreglos es \n{arr_r2}")

La suma de ambos arreglos es 
[11 22 33 44 55]

La diferencia de ambos arreglos es 
[ 9 18 27 36 45]


In [14]:
data_array = np.array([
    [35,10,1,3500,12000],
    [50,25,3,6000,30000],
    [23,2,0,50,1500],
    [42,15,2,1000,2800]
])
print(data_array)

[[   35    10     1  3500 12000]
 [   50    25     3  6000 30000]
 [   23     2     0    50  1500]
 [   42    15     2  1000  2800]]


In [15]:
type(data_array)

numpy.ndarray